openapi: 3.0.0
info:
  description: Our City App internal apis
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Our City App
  version: 0.0.1
servers:
- url: https://localhost:8333/api
security:
- ApiKeyAuth: []
paths:
  /homescreen/{communityId}/{homeScreenId}:
    post:
      operationId: update_home_screen
      parameters:
      - description: The id of the community to which this home screen belongs
        explode: false
        in: path
        name: communityId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      - description: The id of the home screen
        explode: false
        in: path
        name: homeScreenId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HomeScreen'
      responses:
        "204":
          description: Request was successful
      summary: Saves the home screen for a community
      x-openapi-router-controller: oca.controllers.default_controller
components:
  schemas:
    HomeScreen:
      example:
        bottom_navigation:
          buttons:
          - icon: fa-envelope
            action: action
            label: Messages
          - icon: fa-external-link
            action: https://google.com
            label: Google
        bottom_sheet:
          header:
            image: image
            subtitle: subtitle
            title: title
          rows:
          - key: '{}'
          - key: '{}'
        translations:
          en:
            news: News
            trash_calendar: Trash calendar
          nl:
            news: Nieuws
            trash_calendar: Afvalkalender
        default_language: en
        version: 0
        content:
          embedded_app: embedded_app
          type: native
          service_email: service_email
      properties:
        version:
          format: int32
          type: integer
        content:
          $ref: '#/components/schemas/HomeScreenContent'
        bottom_navigation:
          $ref: '#/components/schemas/HomeScreenBottomNavigation'
        bottom_sheet:
          $ref: '#/components/schemas/HomeScreenBottomSheet'
        default_language:
          description: Language to use when the user his language is not one of the
            available ones in the translation mapping
          example: en
          type: string
        translations:
          additionalProperties:
            additionalProperties:
              description: Translated strings
              type: string
            description: Translation keys
            type: object
          description: Translations for any string which could be translated on the
            homescreen. Properties that should be translated should contain a $ prefix.
            For example, label -> $trash_calendar
          example:
            en:
              news: News
              trash_calendar: Trash calendar
            nl:
              news: Nieuws
              trash_calendar: Afvalkalender
          type: object
      required:
      - bottom_navigation
      - bottom_sheet
      - content
      - default_language
      - translations
      - version
      type: object
    HomeScreenContent:
      description: Content of the homescreen, native or an embedded app
      example:
        embedded_app: embedded_app
        type: native
        service_email: service_email
      properties:
        type:
          enum:
          - native
          - embedded_app
          type: string
        embedded_app:
          description: Only set when 'type' is embedded_app
          type: string
        service_email:
          description: This service will be used as 'context' in the embedded app,
            to set user data / service data.
          type: string
      required:
      - type
    HomeScreenBottomNavigation:
      description: Content of the bottom navigation bar
      example:
        buttons:
        - icon: fa-envelope
          action: action
          label: Messages
        - icon: fa-external-link
          action: https://google.com
          label: Google
      properties:
        buttons:
          items:
            $ref: '#/components/schemas/HomeScreenNavigationButton'
          type: array
    HomeScreenNavigationButton:
      description: A button shown in the bottom navigation of the app
      properties:
        icon:
          type: string
        label:
          type: string
        action:
          type: string
      required:
      - action
      - icon
      - label
      type: object
    HomeScreenBottomSheet:
      example:
        header:
          image: image
          subtitle: subtitle
          title: title
        rows:
        - key: '{}'
        - key: '{}'
      properties:
        header:
          $ref: '#/components/schemas/HomeScreenBottomSheetHeader'
        rows:
          items:
            additionalProperties: true
            type: object
          type: array
      required:
      - header
      - rows
      type: object
    HomeScreenBottomSheetHeader:
      example:
        image: image
        subtitle: subtitle
        title: title
      properties:
        title:
          type: string
        subtitle:
          nullable: true
          type: string
        image:
          nullable: true
          type: string
      required:
      - title
      type: object
  securitySchemes:
    ApiKeyAuth:
      description: Shared secret between servers
      in: header
      name: X-OCA3-Api-Key
      type: apiKey
      x-apikeyInfoFunc: oca.controllers.security_controller_.info_from_ApiKeyAuth
